# Generated by Django 2.0.5 on 2018-07-14 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='pic_url',
            field=models.ImageField(blank=True, default='C:\\code-final\\tripapp-1\\account\\static\\account\\default-avatar.jpg', null=True, upload_to=''),
        ),
    ]
